import "./reset.css";
import "./scss/style.css";

export const metadata = {
  title: "JHS-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>{children}</body>
    </html>
  );
}
